class SessionsController < ApplicationController

  def new

    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
    #verify password

    if user
      session[:session_token] = user.session_token
      login!(user)
      redirect_to cats_url
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

#shaky on how to translate between different syntactic sugar for hashlike objects
#length: { minimum: 6 } vs. params[:user][:user_name] vs. params(user: user_name) vs.  only: [:new, :create]
#in params there's an outer key of user. And that outer key is equal to an object. So params is an object which has a key of user ...
#double indexing into nested user hashes


#how does params[:user][:user_name] translate to user_name? What does :user mean?



#params is a hash that gets generated for us based on parameters generated by that http request
# how you're nesting the information when you're inputting the form
# like when we were testing stuff in postman
# user[username]
# user is the


#More questions: 

#what is the first outer session key in session[:session_token]?

#On line 9, should we be using an instance variable or a local one?